# Generated by Django 4.2.5 on 2023-11-07 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_qadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="context_id",
        ),
    ]
